### PR TITLE
Look for TriFingerPro config in home directory rather than in the package

### PR DESCRIPTION
**Pull request by luator**
## Description

For the TriFingerPro platforms, we have different config files (due to different home offsets) for otherwise identical platforms.  To make it easier to maintain this, the scripts for TriFingerPro robots are now not using the config file from the package anymore but instead expect it to be located at `~/.config/trifingerpro/trifingerpro.yml`.  So when setting up a new PC, the config file from this repo should be used as a template and be copied there.  Then the home offsets can be changed there.

For this to be possible, the `Robot` class is extended a bit to also accept absolute paths to config files (they need to start with "/").

## How I Tested

On one TriFingerPro platform (running the demo).

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Review by mwuethri — COMMENTED** [review]
i am not sure i understand how you are handling the config files currently. are the config files for each platform somewhere in a repo, or only local?

i think it would be good to have them in a repo, for simplicity i guess i would keep them all checked into this repo, with the according robot name. 

then, instead of having a robotconfig called trifingerpro (in robot.py), we could have robotconfigs for each specific robot.

does this make sense? it's possible that i did not fully understand the situation.

**Comment by luator** [comment]
@mwuethri There are a few reasons why I don't want to add them to the repo:
- The files would all be identical except for the home offset.  The home offset itself may change often (everytime a finger is removed for maintenance) so it would be some organisational overhead to keep git updated with the changes.  Also these offsets can be determined within a minute, so there is not really a need to have a backup on git.
- It is easier to load the config if it is found at the same location for each robot.  With separate files, we would need to let the software know on which robot it is running, so it loads the correct file.
- The package will later be installed inside a Singularity image.  So each time some offsets change, we would need to update the image.

Even if we want to manage them in git, we could still do this with this PR by adding them in the repo and then making a symlink at ~/.config/trifingerpro to the correct file (this would resolve the second point above).

**Comment by mwuethri** [comment]
OK, I see. The point which is not clear to me yet: What's the procedure if a new user wants to use the robot? Then they have to find the home offsets themselves? I think this would not be ideal because of the potential for error, and also because then things might not be reproducible between users.

**Review by mwuethri — APPROVED** [review]

**Comment by luator** [comment]
As the TriFingerPros are supposed to be operated through the submission system, there will be only one user on the robot PC.  So I don't think this should really be a problem.

**Comment by mwuethri** [comment]
OK, sounds good :)

**Pull request merged**
